[act]

% exception.cc.bin

[assert]

stderr equals <<EOF
[----] exception::raise_any: Caught some unexpected exception during the test execution.
[FAIL] exception::raise_any
[----] exception::raise_any_fini: Caught some unexpected exception during the test finalization.
[----] exception::raise_any_init: Caught some unexpected exception during the test initialization.
[FAIL] exception::raise_any_init
[----] exception::raise_std: Caught an unexpected exception during the test execution: Some exception message.
[FAIL] exception::raise_std
[----] exception::raise_std_fini: Caught an unexpected exception during the test finalization: Some exception message.
[----] exception::raise_std_init: Caught an unexpected exception during the test initialization: Some exception message.
[FAIL] exception::raise_std_init
[====] Synthesis: Tested: 6 | Passing: 2 | Failing: 4 | Crashing: 0 
EOF
